spring:
  datasource:
    url: jdbc:mysql://114.118.13.198:3306/tb_order?characterEncoding=utf-8
    username: lifucang
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8888/eureka



